# the indtance Id for logging identification purposes
Id = "OxKube-01"
LogLevel = "Trace"

# CMDB endpoint to update
[Onix]
    URL = "http://localhost:8080"
    AuthMode = "basic"
    Username = "admin"
    Password = "0n1x"
    ClientId = ""
	ClientSecret = ""
	TokenURI = ""

# event consumers
[Consumers]
    # selected event consumer (i.e. webhook, broker)
    Consumer = 'webhook'

    # webhook consumer details
    [Consumers.Webhook]
        Port = "8000"
        Path = "webhook"

    # broker consumer details
    [Consumers.Broker]
