---
apiVersion: v1
kind: Pod
metadata:
  name: demo
  namespace: demo-project
spec:
  containers:
    - image: nginxdemos/hello
      imagePullPolicy: Always
      name: demo
      resources:
        requests:
          memory: "0.5Gi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "500m"
  restartPolicy: Always
...