---
apiVersion: v1
kind: ReplicationController
metadata:
  name: demo-rc
spec:
  replicas: 1
  selector:
    app: demo
  template:
    metadata:
      name: demo-rc
      labels:
        app: demo
    spec:
      containers:
        - image: nginxdemos/hello
          imagePullPolicy: Always
          name: demo
          resources:
            requests:
              memory: "0.5Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      restartPolicy: Always
...