---
apiVersion: v1
kind: Service
metadata:
  name: echo-app-svc
  namespace: echo-app-project
  labels:
    app: echo-app
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: echo-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
...